#ifndef SEGMENTATIONCORE_GLOBAL_H
#define SEGMENTATIONCORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SEGMENTATIONCORE_LIBRARY)
#  define SEGMENTATIONCORESHARED_EXPORT Q_DECL_EXPORT
#else
#  define SEGMENTATIONCORESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SEGMENTATIONCORE_GLOBAL_H
