#ifndef PMSDP_MATLAB_PROXY_GLOBAL_H
#define PMSDP_MATLAB_PROXY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PMSDP_MATLAB_PROXY_LIBRARY)
#  define PMSDP_MATLAB_PROXYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PMSDP_MATLAB_PROXYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PMSDP_MATLAB_PROXY_GLOBAL_H
