#ifndef REGISTRATIONCORE_GLOBAL_H
#define REGISTRATIONCORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(REGISTRATIONCORE_LIBRARY)
#  define REGISTRATIONCORESHARED_EXPORT Q_DECL_EXPORT
#else
#  define REGISTRATIONCORESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // REGISTRATIONCORE_GLOBAL_H
