#ifndef OPTIMIZATIONCORE_GLOBAL_H
#define OPTIMIZATIONCORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(OPTIMIZATIONCORE_LIBRARY)
#  define OPTIMIZATIONCORESHARED_EXPORT Q_DECL_EXPORT
#else
#  define OPTIMIZATIONCORESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // OPTIMIZATIONCORE_GLOBAL_H
