#ifndef DIMENSIONREDUCTION_GLOBAL_H
#define DIMENSIONREDUCTION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DIMENSIONREDUCTION_LIBRARY)
#  define DIMENSIONREDUCTIONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DIMENSIONREDUCTIONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DIMENSIONREDUCTION_GLOBAL_H
